//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Race
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Race()
        {
            this.Registrations = new HashSet<Registration>();
        }
    
        public int raceID { get; set; }
        public double distance { get; set; }
        public System.DateTime date { get; set; }
        public string name { get; set; }
        public int minStartNumber { get; set; }
        public int maxStartNumber { get; set; }
        public string type { get; set; }
        public double startFarePrice { get; set; }
        public string Chronometer_email { get; set; }
        public int Event_eventID { get; set; }
    
        public virtual Chronometer Chronometer { get; set; }
        public virtual Event Event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registration> Registrations { get; set; }
    }
}
